version: 2
jobs:
  test:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      # restore folders with npm dependencies and Cypress binary
      - restore_cache:
          keys:
            - cache-{{ checksum "package.json" }}
      # install npm dependencies and Cypress binary
      # if they were cached, this step is super quick
      - run:
          name: Install dependencies
          command: npm ci
      - run: npx cypress run --reporter junit --reporter-options "mochaFile=results/results.xml"

      # upload test results
      - store_test_results:
          path: /root/project/cypress/test-results.xml

      - store_artifacts:
          path: /root/project/cypress/

workflows:
  version: 2
  build:
    jobs:
      - test