# to use orbs, must use version >= 2.1
version: 2.1
orbs:
  # import Cypress orb by specifying an exact version x.y.z
  # or the latest version 1.x.x using "@1" syntax
  cypress: cypress-io/cypress@1
jobs:
  e2e:
    - cypress/run
workflows:
  version: 2
  build:
    jobs:
      # "cypress" is the name of the imported orb
      # "run" is the name of the job defined in Cypress orb
      e2e
    nightly:
      triggers:
        - schedule:
            cron: "* * * * *"
            filters:
              branches:
                only:
                  - master
                  - beta
    jobs:
       - e2e
      
